# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/feddockh/codingProjects/3M_Application

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/feddockh/codingProjects/3M_Application

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/feddockh/codingProjects/3M_Application/CMakeFiles /home/feddockh/codingProjects/3M_Application/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/feddockh/codingProjects/3M_Application/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Modal-main.exe

# Build rule for target.
Modal-main.exe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Modal-main.exe
.PHONY : Modal-main.exe

# fast build rule for target.
Modal-main.exe/fast:
	$(MAKE) -f CMakeFiles/Modal-main.exe.dir/build.make CMakeFiles/Modal-main.exe.dir/build
.PHONY : Modal-main.exe/fast

#=============================================================================
# Target rules for targets named Modal-tests

# Build rule for target.
Modal-tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Modal-tests
.PHONY : Modal-tests

# fast build rule for target.
Modal-tests/fast:
	$(MAKE) -f CMakeFiles/Modal-tests.dir/build.make CMakeFiles/Modal-tests.dir/build
.PHONY : Modal-tests/fast

Modal.o: Modal.cpp.o

.PHONY : Modal.o

# target to build an object file
Modal.cpp.o:
	$(MAKE) -f CMakeFiles/Modal-main.exe.dir/build.make CMakeFiles/Modal-main.exe.dir/Modal.cpp.o
	$(MAKE) -f CMakeFiles/Modal-tests.dir/build.make CMakeFiles/Modal-tests.dir/Modal.cpp.o
.PHONY : Modal.cpp.o

Modal.i: Modal.cpp.i

.PHONY : Modal.i

# target to preprocess a source file
Modal.cpp.i:
	$(MAKE) -f CMakeFiles/Modal-main.exe.dir/build.make CMakeFiles/Modal-main.exe.dir/Modal.cpp.i
	$(MAKE) -f CMakeFiles/Modal-tests.dir/build.make CMakeFiles/Modal-tests.dir/Modal.cpp.i
.PHONY : Modal.cpp.i

Modal.s: Modal.cpp.s

.PHONY : Modal.s

# target to generate assembly for a file
Modal.cpp.s:
	$(MAKE) -f CMakeFiles/Modal-main.exe.dir/build.make CMakeFiles/Modal-main.exe.dir/Modal.cpp.s
	$(MAKE) -f CMakeFiles/Modal-tests.dir/build.make CMakeFiles/Modal-tests.dir/Modal.cpp.s
.PHONY : Modal.cpp.s

Modal_main.o: Modal_main.cpp.o

.PHONY : Modal_main.o

# target to build an object file
Modal_main.cpp.o:
	$(MAKE) -f CMakeFiles/Modal-main.exe.dir/build.make CMakeFiles/Modal-main.exe.dir/Modal_main.cpp.o
.PHONY : Modal_main.cpp.o

Modal_main.i: Modal_main.cpp.i

.PHONY : Modal_main.i

# target to preprocess a source file
Modal_main.cpp.i:
	$(MAKE) -f CMakeFiles/Modal-main.exe.dir/build.make CMakeFiles/Modal-main.exe.dir/Modal_main.cpp.i
.PHONY : Modal_main.cpp.i

Modal_main.s: Modal_main.cpp.s

.PHONY : Modal_main.s

# target to generate assembly for a file
Modal_main.cpp.s:
	$(MAKE) -f CMakeFiles/Modal-main.exe.dir/build.make CMakeFiles/Modal-main.exe.dir/Modal_main.cpp.s
.PHONY : Modal_main.cpp.s

Modal_test.o: Modal_test.cpp.o

.PHONY : Modal_test.o

# target to build an object file
Modal_test.cpp.o:
	$(MAKE) -f CMakeFiles/Modal-tests.dir/build.make CMakeFiles/Modal-tests.dir/Modal_test.cpp.o
.PHONY : Modal_test.cpp.o

Modal_test.i: Modal_test.cpp.i

.PHONY : Modal_test.i

# target to preprocess a source file
Modal_test.cpp.i:
	$(MAKE) -f CMakeFiles/Modal-tests.dir/build.make CMakeFiles/Modal-tests.dir/Modal_test.cpp.i
.PHONY : Modal_test.cpp.i

Modal_test.s: Modal_test.cpp.s

.PHONY : Modal_test.s

# target to generate assembly for a file
Modal_test.cpp.s:
	$(MAKE) -f CMakeFiles/Modal-tests.dir/build.make CMakeFiles/Modal-tests.dir/Modal_test.cpp.s
.PHONY : Modal_test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... test"
	@echo "... Modal-main.exe"
	@echo "... Modal-tests"
	@echo "... Modal.o"
	@echo "... Modal.i"
	@echo "... Modal.s"
	@echo "... Modal_main.o"
	@echo "... Modal_main.i"
	@echo "... Modal_main.s"
	@echo "... Modal_test.o"
	@echo "... Modal_test.i"
	@echo "... Modal_test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

